[tool.poetry]
name = "dlrs-release"
version = "v0.0.0-RELEASE"
description = "Image docker para deploy de aplicações"
authors = ["Lucas Cantarelli <lucascantarellijpa@gmail.com>"]
readme = "README.md"