name: Develop

on:
    workflow_call:
    workflow_dispatch: 
jobs:
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest
        env:
          PREFIX: "dlrs"
          FIELDS: (name,version)

        steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Create Variables file
          #uses: dolorestec/devops/.github/workflows/validate.yml@v1
          run: touch variables.txt

        - name: Export variables
          run: |
            for i in $FIELDS; do
              print $( echo $i | grep $i | awk -F, '{print $1}')
              echo $i | grep -e $i | awk '{print $1}'
            done
            