name: Develop

on:
    workflow_call:
    workflow_dispatch: 
jobs:
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest
        env:
          DLRS_NAME: $(cat pyproject.toml | grep name | awk -F'=' '{print $0}' | sed 's/ \|"\|//g')
          DLRS_VERSION: $(cat pyproject.toml | grep version | awk -F'=' '{print $0}' | sed 's/ \|"\|//g')
          DLRS_LAST_VERSION: "$(git tag --sort creatordate -l 'v*-RELEASE*' 'v*-RC*' --merged | tail -n 1)"

        steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Environment variables
          run: env | grep DLRS

        - name: Create Variables file
          #uses: dolorestec/devops/.github/workflows/validate.yml@v1
          run: touch variables.txt

        - name: Environment variables
          run: |
            env | grep DLRS >> variables.txt

        - name: Create Variables file
          run: cat variables.txt