name: Develop
run-name: Push Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:  
  setup:
    name: Setup environment
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/setup-environment.yml@develop

  publish:
    name: Docker publish
    needs: setup
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/docker-publish.yml@develop
  
  release:
    name: Release gitflow
    needs: publish
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/release-gitflow.yml@develop