name: Develop

on:
    workflow_call:
    workflow_dispatch: 

jobs:
    variables:
        name: Export variables
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Create variables
          run: |
            echo "Exporting variables to Variables file"
            touch variables.txt
            echo -e "DLRS_NAME=$(pwd | awk -F'/' '{print $NF}')" >> variables.txt
            echo "DLRS_VERSION=$(cat pyproject.toml | grep version | awk -F'=' '{print $2}' | sed 's/ \|"\|//g')" >> variables.txt
            echo "DLRS_LAST_VERSION=$(git tag --sort creatordate -l 'v*-RELEASE*' 'v*-RC*' --merged | tail -n 1)" >> variables.txt
          #uses: dolorestec/devops/.github/workflows/validate.yml@v1
          
        - name: Upload variables
          uses: actions/upload-artifact@v3
          with:
            name: variables.txt
            path: variables.txt

    build:
      name: Build
      needs: [variables]
      runs-on: ubuntu-latest
      steps:
        - name: Download variables
          uses: actions/download-artifact@v2
          with:
            name: variables.txt
        - name: Set variables
          shell: bash
          run: |
              cat variables.txt
              cat variables.txt | xargs -I {} echo "export {}"

        - name: Set variables
          shell: bash
          run: |
            cat variables.txt | xargs -I {} echo "{}" >> $GITHUB_ENV
        
        - name: Build
          run: |
            env


