name: Develop

on:
    workflow_call:
    workflow_dispatch: 
jobs:
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest
        env:
          PREFIX: "dlrs"

        steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Environment variables
          run: env

        - name: Create Variables file
          #uses: dolorestec/devops/.github/workflows/validate.yml@v1
          run: touch variables.txt

        - name: Export variables to file
          run: |
            echo "export $PREFIX-$(cat pyproject.toml | grep name | awk -F'=' '{print $0}' | sed 's/ \|"\|//g')" >> variables.txt
            echo "export $PREFIX-$(cat pyproject.toml | grep version | awk -F'=' '{print $0}' | sed 's/ \|"\|//g')" >> variables.txt
            echo "export $PREFIX-LAST_VERSION=$(git tag --sort creatordate -l "v*-RELEASE*" "v*-RC*" --merged | tail -n 1)" >> variables.txt
            