name: Develop
run-name: Push Develop

on:
  workflow_call:
  workflow_dispatch:

jobs:  
  environment:
    name: Setup Environment
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/prepare-environment.yml@develop

  build:
    name: Docker Build
    needs: environment
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/docker-build.yml@develop

  deploy:
    name: Docker Deploy
    needs: build
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/docker-deploy.yml@develop
  
  branch:
    name: Create Branch
    needs: deploy
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/release-branch.yml@develop