name: Develop
run-name: Push Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:  
  setup:
    name: Environment
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/setup-environment.yml@develop

  publish:
    name: Docker
    needs: setup
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/docker-build-push.yml@develop
  
  release:
    name: Create
    needs: publish
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/release-branch.yml@develop