name: Develop
run-name: Push Develop

on:
  workflow_call:
  workflow_dispatch:

jobs:  
  setup:
    name: Setup Environment
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/prepare-environment.yml@develop

  publish:
    name: Docker Build and Push
    needs: setup
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/docker-build-push.yml@develop
  
  release:
    name: Create Branch
    needs: publish
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/release-branch.yml@develop