name: Develop
run-name: Push Develop

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  environment:
    name: Environment 
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/prepare-environment.yml@develop

  build:
    name: Build
    needs: environment
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/docker-build.yml@develop

  deploy:
    name: Deploy
    needs: build
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/docker-deploy.yml@develop

  release:
    name: Release
    needs: deploy
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/release-branch.yml@develop