name: Develop

on:
    workflow_call:
    workflow_dispatch: 
jobs:
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Environment variables
          run: env

        - name: Create Variables file
          #uses: dolorestec/devops/.github/workflows/validate.yml@v1
          run: touch variables.txt

        - name: Environment variables
          env:
              DLRS_NAME: $(cat pyproject.toml | grep name | awk -F'=' '{print $0}' | sed 's/ \|"\|//g')
              DLRS_VERSION: $(cat pyproject.toml | grep version | awk -F'=' '{print $0}' | sed 's/ \|"\|//g')
              DLRS_LAST_VERSION: "$(git tag --sort creatordate -l 'v*-RELEASE*' 'v*-RC*' --merged | tail -n 1)"
              DLRS_LAST_RELEASE: git tag --sort creatordate -l 'v*-RELEASE*' --merged | tail -n 1)
          run: |
            env | grep DLRS >> variables.txt
            echo $DLRS_NAME
            echo $DLRS_VERSION
            echo $DLRS_LAST_VERSION
            echo $DLRS_LAST_RELEASE
            

        - name: Create Variables file
          run: cat variables.txt