name: Develop
run-name: Push Develop

on:
  workflow_call:
  workflow_dispatch:

jobs:  
  setup:
    name: Setup Environment
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/setup-environment.yml@develop

