name: Develop

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  environment:
    name: Environment 
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/prepare-environment.yml@develop

  validade:
    name: Validate
    needs: environment
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/docker-test.yml@develop

  deploy:
    name: Deploy
    needs: validade
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/docker-deploy.yml@develop