name: Develop

on:
    workflow_call:
    workflow_dispatch: 
jobs:
    variables:
        name: Variables
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: Actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Variables
          run: |
            cat pyproject.toml | grep name
            cat pyproject.toml | grep version