name: Develop
run-name: Push Develop

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  release:
    name: Release Branch
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/release-branch.yml@develop
    
