name: First Run Branch [release, hotfix]
run-name: Publish snapshot

on:
  workflow_run:
    workflows: ["Gitflow workflow"]
    branches: [release/*, hotfix/*]
    types:
      - completed

jobs:  
  setup:
    name: Setup environment
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/setup-environment.yml@develop

  publish:
    name: Docker publish
    needs: setup
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/docker-publish.yml@develop