name: Push on [main,develop]
run-name: Push Workflow

on:
  workflow_dispatch:

jobs:  
  setup:
    name: Setup environment
    uses: dolorestec/devops/.github/workflows/setup-environment.yml@develop
    with:
      env_file: ${{ format('{0}.env',github.event.repository.name) }}
      version_file: ${{ format('{0}.json',github.event.repository.name) }}
      variables: |
        {
          "DLRS_PKG_NAME":"${{ github.event.repository.name }}",
          "DLRS_PKG_VERSION":"$(cat ${{ format('{0}.json',github.event.repository.name) }} | grep version | awk -F':' '{print $2}' | sed 's/ \|"\|//g' | awk -F'-' '{print $1}' | sed 's/[^0-9.]*//g')",
          "DLRS_PKG_REPOSITORY":"${{ github.repository }}",
          "DLRS_PKG_BRANCH":"${{ github.ref_name }}",
          "DLRS_TAG":"$(cat ${{ format('{0}.env',github.event.repository.name) }} | grep version | awk -F':' '{print $2}' | sed 's/ \|"\|//g')"
        }

        
#DLRS_PKG_NAME=${{ github.event.repository.name }}
#DLRS_PKG_VERSION=$(cat ${{ format('{0}.json',github.event.repository.name) }} | grep version | awk -F':' '{print $2}' | sed 's/ \|"\|//g' | awk -F'-' '{print $1}' | sed 's/[^0-9.]*//g')
#DLRS_PKG_REPOSITORY=${{ github.repository }}
#DLRS_PKG_BRANCH=${{ github.ref_name }}
#DLRS_TAG=$(cat ${{ format('{0}.env',github.event.repository.name) }} | grep version | awk -F':' '{print $2}' | sed 's/ \|"\|//g')


#  publish:
#    name: Docker publish
#    needs: setup
#    secrets: inherit
#    uses: dolorestec/devops/.github/workflows/docker-publish.yml@develop
  
#  release:
#    name: Gitflow Workflow
#    needs: publish
#    secrets: inherit
#    uses: dolorestec/devops/.github/workflows/release-gitflow.yml@develop