name: Develop
run-name: Push Develop

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  environment:
    name: Environment
    secrets: inherit
    uses: dolorestec/devops/.github/workflows/environment.yml@develop